### ISSUE TITLE
Error `AWS object not present or incorrect in the constructor` when using IAM role

### ISSUE THREAD

**Issue by dchertousov** [ghdna/athena-express#21] opened 2019-11-12 15:28 UTC
When IAM role is used for EC2/Lambda and `s3` options is not passed to the config, `athena-express` is not able to create new buckets on its behalf, failing with error `AWS object not present or incorrect in the constructor`.

It looks here:
https://github.com/ghdna/athena-express/blob/master/lib/athenaExpress.js#L232
that it expects either `s3` option to be set or credentials keys to be passed.

I had IAM role set up with full access to S3 and Athena, though I had to specify S3 location manually to override behavior.

**Comment by ghdna** [comment] 2019-11-12 15:44
With IAM role in a Lambda or EC2, you can skip configuring the AWS object with access/secret keys but you still need to pass the AWS object for athena-express to pull the relevant methods off the SDK. Make sure you `const aws = require("aws-sdk");` in your Lambda/EC2 and then pass it in the athena-express constructor.

**Comment by dchertousov** [comment] 2019-11-12 15:56
@ghdna thank you fro swift reply. I pass `aws` config just as you describe `const aws = require("aws-sdk");` but I still receive the error above on the machine where just IAM role is attached and none credentials are configured view `aws configure`. All other AWS services like `s3` work using the same `aws` object instance. Roles permissions are set just as you described (full access for `s3` and `Athena`).

**Comment by ghdna** [comment] 2019-11-12 18:36
oh okay, let me look into it. When IAM roles are attached, I use info from the aws object to create a unique S3 bucket name. If there is an issue with that, perhaps the temporary workaround, until i investigate this, is to provide your own unique s3 bucket name.

**Comment by SamuelHaleMN** [comment] 2020-02-17 03:25
I can confirm that I'm also having this issue.

Executing within a Lamba, with an IAM policy attached to it.

Getting the same error message.

**Comment by ghdna** [comment] 2020-04-05 22:23
Did this get fixed? I tried replicating it but couldnt. 
Can you check if the IAM role has Athena and S3 access. And does it work if you provide s3://yourbucketname in the config?

**Comment by sonupsp3** [comment] 2020-04-20 03:43
Even I'm facing the same issue but with the nodejs.  I tried even by supplying s3 in the config

**Comment by sonupsp3** [comment] 2020-04-20 03:45
I'm using athena-express in java script by passing awsCredentials and also specified s3

**Comment by carlosescura** [comment] 2020-07-07 19:03
Same issue here, when I use profiles in my computer or access keys it works, but when it uses the `AssumeRoleWithWebIdentity` in K8s it fails

**Comment by carlosescura** [comment] 2020-07-07 21:04
After a further investigation, I found the issue and why it's related only with roles:

[This line](https://github.com/ghdna/athena-express/blob/master/lib/helpers.js#L215) is the cause.

For all of you having this issue, can you specify a custom s3 output directory for your queries? 
If so, it won't fail as the exception is thrown because of the lack of both, the `s3` value in the constructor, and the lack of a valid AWS access key (because you are using a `role`/`instanceprofile`).

```
const aws = require("aws-sdk");

const athenaExpressConfig = {
	aws,
	s3: "s3://whatever-your-bucket-is"
};
const athenaExpress = new AthenaExpress(athenaExpressConfig);
```

**Comment by KrickyKiki** [comment] 2020-07-14 10:33
I had this error when trying to pass AWS ( caps ) instead of aws. To replicate the issue:
`const AWS = require("aws-sdk");
const athenaExpressConfig = {
	AWS
};
const athenaExpress = new AthenaExpress(athenaExpressConfig);`

However below worked fine:
`const AWS = require("aws-sdk");
const athenaExpressConfig = {
	aws: AWS
};
const athenaExpress = new AthenaExpress(athenaExpressConfig);`

**Comment by SamuelHaleMN** [comment] 2020-07-14 13:08
> I had this error when trying to pass AWS ( caps ) instead of aws. To replicate the issue:
> 
> ```
> const AWS = require("aws-sdk");
> const athenaExpressConfig = {
> 	AWS
> };
> const athenaExpress = new AthenaExpress(athenaExpressConfig);
> ```
> 
> However below worked fine:
> 
> ```
> const AWS = require("aws-sdk");
> const athenaExpressConfig = {
> 	aws: AWS
> };
> const athenaExpress = new AthenaExpress(athenaExpressConfig);
> ```

This was my issue as well.
It was specifically replicable when passing the all-caps instance of the aws-sdk, labeled as 'AWS' into the AthenaExpress constructor.

**Comment by ghdna** [comment] 2021-04-25 14:49
Closing this issue. Based on the comments, this was not an issue with code and instead an issue with the examples in readme. The uppercase of `AWS` in `const AWS = require("aws-sdk")` mismatched when passing it to AthenaExpress configuration in lowercase. I have updated the readme examples to make following easier. Thanks for bringing this to our notice. If there is still an issue with this, let me know and I'll reopen.

**Closed by ghdna** 2021-04-25 14:49 UTC

**Comment by msokolov93** [comment] 2021-10-05 10:48
const aws = require("aws-sdk");

const athenaExpressConfig = {
	aws,
	s3: "s3://whatever-your-bucket-is"
};
const athenaExpress = new AthenaExpress(athenaExpressConfig);


Had the same issue. After s3 path was added Athena worked and saved files to LOCATION from its tables; not the s3 path added in AthenaExpress configuration.
